/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package log_percentiles

import java.io.File

const val READ_API_REGEX = """([^\s]+)\s+([^\s]+)\s+\"GET\s+([^\s]+)\"\s+([^\s]+)\s+([^\s]+)"""
const val MAX_RESPONSE_TIME = 24 * 60 * 60 * 1000

fun calcPercentiles(dir: String, percentiles: Array<Double> = arrayOf(0.9, 0.95, 0.99)): List<Int> {

    val regex = READ_API_REGEX.toRegex()
    val f = File(dir)
    if(!f.isDirectory) {
        throw Exception("${dir} is not a directory")
    }
    val ftw = f.walk()
    val respTimes = ArrayList<Int>()
    // 时间复杂度O(n)，空间复杂度O(n)
    for(file in ftw.iterator()) {
        if(file.isDirectory || !file.name.endsWith(".log")) {
            continue
        }
        val newRespTimes = file.readLines().asSequence()
            .map { regex.matchEntire(it)?.destructured?.component5()?.toInt() }
            .filterNotNull()
            .toList()
        respTimes.addAll(newRespTimes)
    }
    // 时间复杂度O(n*logn)，空间复杂度O(n*logn)
    respTimes.sort()
    // println("${respTimes.size}")
    return percentiles.asSequence()
        .map { respTimes[(respTimes.size * it).toInt()] }
        .toList()
}

fun main() {
    val dir = "/var/log/httpd" 
    val percentiles = arrayOf(0.9, 0.95, 0.99)
    // val dir = "src/test/resources" 
    val (perc_90, perc_95, perc_99) = calcPercentiles(dir, percentiles)
    println("90% of requests return a response in ${perc_90} ms")
    println("95% of requests return a response in ${perc_95} ms")
    println("99% of requests return a response in ${perc_99} ms")
}
